//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/ProyectoIntegradorAvance/Controles/MisAccionesDeEntrada.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/ProyectoIntegradorAvance/Controles/MisAccionesDeEntrada.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MisAccionesDeEntrada: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MisAccionesDeEntrada()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MisAccionesDeEntrada"",
    ""maps"": [
        {
            ""name"": ""MiMapaDeAcciones"",
            ""id"": ""0f578f66-5839-4dfc-8e03-011dd387f5f0"",
            ""actions"": [
                {
                    ""name"": ""caminaradelante"",
                    ""type"": ""Button"",
                    ""id"": ""7f480a7d-15ed-4c5a-aeca-cbf986db61cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""caminaratras"",
                    ""type"": ""Button"",
                    ""id"": ""2a9379f3-1373-4dbe-9a48-1c318cb92b6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""agachar"",
                    ""type"": ""Button"",
                    ""id"": ""073f9375-86e5-42c4-b6bc-9091a22db9a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""saltar"",
                    ""type"": ""Button"",
                    ""id"": ""fc379c36-5616-4e33-b475-4ecb3ceb90b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""correr"",
                    ""type"": ""Button"",
                    ""id"": ""0bdc36cf-43fd-4c69-99b4-daa70ccb5a74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""disparar"",
                    ""type"": ""Button"",
                    ""id"": ""458a4a4b-631d-40d4-9d87-dd0910f79ec0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f233b7b6-8e33-4a23-89e9-7394b7c9937b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""caminaradelante"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec2870ca-5c77-4aad-8571-29e52af8f900"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""caminaratras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5945445-f993-47c2-803b-583929d55a52"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""agachar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b79858ec-1428-455d-9463-0e4c8b51f8e8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb53a49a-db35-40ec-823f-ec468ad9ab51"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""correr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04f91aea-eca4-4f20-b600-b33158650fbe"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""disparar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Accionesdeentrada"",
            ""bindingGroup"": ""Accionesdeentrada"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // MiMapaDeAcciones
        m_MiMapaDeAcciones = asset.FindActionMap("MiMapaDeAcciones", throwIfNotFound: true);
        m_MiMapaDeAcciones_caminaradelante = m_MiMapaDeAcciones.FindAction("caminaradelante", throwIfNotFound: true);
        m_MiMapaDeAcciones_caminaratras = m_MiMapaDeAcciones.FindAction("caminaratras", throwIfNotFound: true);
        m_MiMapaDeAcciones_agachar = m_MiMapaDeAcciones.FindAction("agachar", throwIfNotFound: true);
        m_MiMapaDeAcciones_saltar = m_MiMapaDeAcciones.FindAction("saltar", throwIfNotFound: true);
        m_MiMapaDeAcciones_correr = m_MiMapaDeAcciones.FindAction("correr", throwIfNotFound: true);
        m_MiMapaDeAcciones_disparar = m_MiMapaDeAcciones.FindAction("disparar", throwIfNotFound: true);
    }

    ~@MisAccionesDeEntrada()
    {
        UnityEngine.Debug.Assert(!m_MiMapaDeAcciones.enabled, "This will cause a leak and performance issues, MisAccionesDeEntrada.MiMapaDeAcciones.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MiMapaDeAcciones
    private readonly InputActionMap m_MiMapaDeAcciones;
    private List<IMiMapaDeAccionesActions> m_MiMapaDeAccionesActionsCallbackInterfaces = new List<IMiMapaDeAccionesActions>();
    private readonly InputAction m_MiMapaDeAcciones_caminaradelante;
    private readonly InputAction m_MiMapaDeAcciones_caminaratras;
    private readonly InputAction m_MiMapaDeAcciones_agachar;
    private readonly InputAction m_MiMapaDeAcciones_saltar;
    private readonly InputAction m_MiMapaDeAcciones_correr;
    private readonly InputAction m_MiMapaDeAcciones_disparar;
    /// <summary>
    /// Provides access to input actions defined in input action map "MiMapaDeAcciones".
    /// </summary>
    public struct MiMapaDeAccionesActions
    {
        private @MisAccionesDeEntrada m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MiMapaDeAccionesActions(@MisAccionesDeEntrada wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/caminaradelante".
        /// </summary>
        public InputAction @caminaradelante => m_Wrapper.m_MiMapaDeAcciones_caminaradelante;
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/caminaratras".
        /// </summary>
        public InputAction @caminaratras => m_Wrapper.m_MiMapaDeAcciones_caminaratras;
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/agachar".
        /// </summary>
        public InputAction @agachar => m_Wrapper.m_MiMapaDeAcciones_agachar;
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/saltar".
        /// </summary>
        public InputAction @saltar => m_Wrapper.m_MiMapaDeAcciones_saltar;
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/correr".
        /// </summary>
        public InputAction @correr => m_Wrapper.m_MiMapaDeAcciones_correr;
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/disparar".
        /// </summary>
        public InputAction @disparar => m_Wrapper.m_MiMapaDeAcciones_disparar;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MiMapaDeAcciones; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MiMapaDeAccionesActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MiMapaDeAccionesActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MiMapaDeAccionesActions" />
        public void AddCallbacks(IMiMapaDeAccionesActions instance)
        {
            if (instance == null || m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces.Add(instance);
            @caminaradelante.started += instance.OnCaminaradelante;
            @caminaradelante.performed += instance.OnCaminaradelante;
            @caminaradelante.canceled += instance.OnCaminaradelante;
            @caminaratras.started += instance.OnCaminaratras;
            @caminaratras.performed += instance.OnCaminaratras;
            @caminaratras.canceled += instance.OnCaminaratras;
            @agachar.started += instance.OnAgachar;
            @agachar.performed += instance.OnAgachar;
            @agachar.canceled += instance.OnAgachar;
            @saltar.started += instance.OnSaltar;
            @saltar.performed += instance.OnSaltar;
            @saltar.canceled += instance.OnSaltar;
            @correr.started += instance.OnCorrer;
            @correr.performed += instance.OnCorrer;
            @correr.canceled += instance.OnCorrer;
            @disparar.started += instance.OnDisparar;
            @disparar.performed += instance.OnDisparar;
            @disparar.canceled += instance.OnDisparar;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MiMapaDeAccionesActions" />
        private void UnregisterCallbacks(IMiMapaDeAccionesActions instance)
        {
            @caminaradelante.started -= instance.OnCaminaradelante;
            @caminaradelante.performed -= instance.OnCaminaradelante;
            @caminaradelante.canceled -= instance.OnCaminaradelante;
            @caminaratras.started -= instance.OnCaminaratras;
            @caminaratras.performed -= instance.OnCaminaratras;
            @caminaratras.canceled -= instance.OnCaminaratras;
            @agachar.started -= instance.OnAgachar;
            @agachar.performed -= instance.OnAgachar;
            @agachar.canceled -= instance.OnAgachar;
            @saltar.started -= instance.OnSaltar;
            @saltar.performed -= instance.OnSaltar;
            @saltar.canceled -= instance.OnSaltar;
            @correr.started -= instance.OnCorrer;
            @correr.performed -= instance.OnCorrer;
            @correr.canceled -= instance.OnCorrer;
            @disparar.started -= instance.OnDisparar;
            @disparar.performed -= instance.OnDisparar;
            @disparar.canceled -= instance.OnDisparar;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MiMapaDeAccionesActions.UnregisterCallbacks(IMiMapaDeAccionesActions)" />.
        /// </summary>
        /// <seealso cref="MiMapaDeAccionesActions.UnregisterCallbacks(IMiMapaDeAccionesActions)" />
        public void RemoveCallbacks(IMiMapaDeAccionesActions instance)
        {
            if (m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MiMapaDeAccionesActions.AddCallbacks(IMiMapaDeAccionesActions)" />
        /// <seealso cref="MiMapaDeAccionesActions.RemoveCallbacks(IMiMapaDeAccionesActions)" />
        /// <seealso cref="MiMapaDeAccionesActions.UnregisterCallbacks(IMiMapaDeAccionesActions)" />
        public void SetCallbacks(IMiMapaDeAccionesActions instance)
        {
            foreach (var item in m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MiMapaDeAccionesActions" /> instance referencing this action map.
    /// </summary>
    public MiMapaDeAccionesActions @MiMapaDeAcciones => new MiMapaDeAccionesActions(this);
    private int m_AccionesdeentradaSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme AccionesdeentradaScheme
    {
        get
        {
            if (m_AccionesdeentradaSchemeIndex == -1) m_AccionesdeentradaSchemeIndex = asset.FindControlSchemeIndex("Accionesdeentrada");
            return asset.controlSchemes[m_AccionesdeentradaSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MiMapaDeAcciones" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MiMapaDeAccionesActions.AddCallbacks(IMiMapaDeAccionesActions)" />
    /// <seealso cref="MiMapaDeAccionesActions.RemoveCallbacks(IMiMapaDeAccionesActions)" />
    public interface IMiMapaDeAccionesActions
    {
        /// <summary>
        /// Method invoked when associated input action "caminaradelante" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCaminaradelante(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "caminaratras" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCaminaratras(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "agachar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAgachar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "saltar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSaltar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "correr" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCorrer(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "disparar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDisparar(InputAction.CallbackContext context);
    }
}
